export const POKEMON__FETCH_BY_NAME = 'pokemon/fetchByName';
export const POKEMON__FETCH_LIST ='pokemon/fetchList';
// export const POKEMON_APP__ADD_POKEMON_WITH_VISIBLE_DETAILS = 'addPokemonWithVisibleDetails';
// export const POKEMON_APP__CHANGE_APP_THEME = 'changeAppTheme';
// export const POKEMON_APP__CHANGE_LIMIT = 'changeLimit';
// export const POKEMON_APP__CHANGE_OFFSET = 'changeOffset';
// export const POKEMON_APP__CHANGE_POKEMON_NAME_FILTER = 'changePokemonNameFilter';
// export const POKEMON_APP__CHANGE_POKEMON_TYPE_FILTER = 'changePokemonTypeFilter';
// export const POKEMON_APP__REMOVE_POKEMON_WITH_VISIBLE_DETAILS = 'removePokemonWithVisibleDetails';
