import {
//   TYPE_FILTER_POKEMON_BY_TYPE_BUG,
//   TYPE_FILTER_POKEMON_BY_TYPE_DARK,
//   TYPE_FILTER_POKEMON_BY_TYPE_DRAGON,
//   TYPE_FILTER_POKEMON_BY_TYPE_ELECTRIC,
//   TYPE_FILTER_POKEMON_BY_TYPE_FAIRY,
//   TYPE_FILTER_POKEMON_BY_TYPE_FIGHTING,
//   TYPE_FILTER_POKEMON_BY_TYPE_FIRE,
//   TYPE_FILTER_POKEMON_BY_TYPE_FLYING,
//   TYPE_FILTER_POKEMON_BY_TYPE_GHOST,
//   TYPE_FILTER_POKEMON_BY_TYPE_GRASS,
//   TYPE_FILTER_POKEMON_BY_TYPE_GROUND,
//   TYPE_FILTER_POKEMON_BY_TYPE_ICE,
//   TYPE_FILTER_POKEMON_BY_TYPE_NORMAL,
//   TYPE_FILTER_POKEMON_BY_TYPE_POISON,
//   TYPE_FILTER_POKEMON_BY_TYPE_PSYCHIC,
//   TYPE_FILTER_POKEMON_BY_TYPE_ROCK,
//   TYPE_FILTER_POKEMON_BY_TYPE_STEEL,
//   TYPE_FILTER_POKEMON_BY_TYPE_WATER,
//   TYPE_FILTER_POKEMON_BY_TYPE_ALL,
  TYPE_CHANGE_POKEMON_TYPE_FILTER,
} from '../config/actionTypes';

const defaultState: any = {
  filter: 'ALL',
};

export default function filterPokemonByTypeReducer(state = defaultState, action: any) {
  switch (action.type) {
    case TYPE_CHANGE_POKEMON_TYPE_FILTER:
      return action.filter;
    default:
      return state;
  }
}
